<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_timeline',
		'title' => 'Timeline',
		'fields' => array (
			array (
				'key' => 'field_531195e84b8f2',
				'label' => 'Posts',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_531193caa0227',
				'label' => 'Display Posts From Blog',
				'name' => 'display_posts',
				'type' => 'radio',
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_540036bf99ca8',
				'label' => 'Enable Thumbnail',
				'name' => 'enable_post_thumbnail',
				'type' => 'radio',
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'no',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53247d0fb1e8b',
				'label' => 'Maximum Number Of Posts',
				'name' => 'max_posts',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_531193caa0227',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 100,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 200,
				'step' => '',
			),
			array (
				'key' => 'field_5311930a0bbfc',
				'label' => 'Select Categories',
				'name' => 'select_categories',
				'type' => 'taxonomy',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_531193caa0227',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'taxonomy' => 'category',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_53247a1696ecb',
				'label' => 'Exclude Posts',
				'name' => 'exclude_posts',
				'type' => 'post_object',
				'instructions' => 'Selected Posts will be excluded from the timeline. You can select multiple posts.',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_531193caa0227',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'post_type' => array (
					0 => 'post',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
			array (
				'key' => 'field_53247e029edbe',
				'label' => 'Authors',
				'name' => 'authors',
				'type' => 'user',
				'instructions' => 'Posts from selected authors will be displayed. Leave blank to display from all authors	',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_531193caa0227',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'role' => array (
					0 => 'all',
				),
				'field_type' => 'multi_select',
				'allow_null' => 1,
			),
			array (
				'key' => 'field_53247eb505226',
				'label' => 'Tags',
				'name' => 'tags',
				'type' => 'taxonomy',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_531193caa0227',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'taxonomy' => 'post_tag',
				'field_type' => 'multi_select',
				'allow_null' => 1,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_531195f84b8f3',
				'label' => 'Twitter',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_531194c3fb8f7',
				'label' => 'Display Tweets',
				'name' => 'display_tweets',
				'type' => 'radio',
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_531194e2fb8f8',
				'label' => 'Twitter Username',
				'name' => 'twitter_username',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_531194c3fb8f7',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '@',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5325f2ec7b133',
				'label' => 'Tweet Count',
				'name' => 'tweet_count',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_531194c3fb8f7',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 100,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 200,
				'step' => '',
			),
			array (
				'key' => 'field_5325f41771c62',
				'label' => 'Refresh Cache (minutes)',
				'name' => 'refresh_feed',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_531194c3fb8f7',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 5,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 5,
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_538d9b68a2383',
				'label' => 'Facebook',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_538d9be2a2385',
				'label' => 'Display Posts',
				'name' => 'display_fbposts',
				'type' => 'radio',
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'no',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53d2afaefd6a0',
				'label' => 'Enable Thumbnail',
				'name' => 'facebook_thumbnail',
				'type' => 'radio',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_538d9be2a2385',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'no',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_538d9c53a2386',
				'label' => 'Facebook Page ID',
				'name' => 'facebook_page_id',
				'type' => 'text',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_538d9be2a2385',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_538d9eaaa238a',
				'label' => 'Post Count',
				'name' => 'post_count',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_538d9be2a2385',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 10,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 5,
				'max' => 25,
				'step' => '',
			),
			array (
				'key' => 'field_538d9dd0a2389',
				'label' => 'Refresh Cache (minutes)',
				'name' => 'refresh_cache',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_538d9be2a2385',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 5,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 5,
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5311960c4b8f4',
				'label' => 'Status Updates',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53119587e3d44',
				'label' => 'Display Status Updates',
				'name' => 'display_status_updates',
				'type' => 'radio',
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53119b7a50726',
				'label' => 'Status Update',
				'name' => 'status_update',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53119587e3d44',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_53119bbc50727',
						'label' => 'Title',
						'name' => 'status_title',
						'type' => 'text',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_5388533113183',
						'label' => 'Date And time',
						'name' => 'status_date',
						'type' => 'date_time_picker',
						'required' => 1,
						'column_width' => '',
						'show_date' => 'true',
						'date_format' => 'm/d/y',
						'time_format' => 'h:mm tt',
						'show_week_number' => 'false',
						'picker' => 'slider',
						'save_as_timestamp' => 'true',
						'get_as_timestamp' => 'true',
					),
					array (
						'key' => 'field_53119bce50728',
						'label' => 'Description',
						'name' => 'status_description',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'formatting' => 'html',
					),
					array (
						'key' => 'field_53bcf0333a3cb',
						'label' => 'Custom Icon',
						'name' => 'custom_icon',
						'type' => 'radio',
						'column_width' => '',
						'choices' => array (
							'default' => 'Default',
							'image' => 'Image',
							'fontawesome' => 'FontAwesome',
						),
						'other_choice' => 0,
						'save_other_choice' => 0,
						'default_value' => 'none : None',
						'layout' => 'horizontal',
					),
					array (
						'key' => 'field_53bcf0833a3cc',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53bcf0333a3cb',
									'operator' => '==',
									'value' => 'image',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_53bcf1683a3cd',
						'label' => 'FontAwesome',
						'name' => 'fontawesome',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53bcf0333a3cb',
									'operator' => '==',
									'value' => 'fontawesome',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Status',
			),
			array (
				'key' => 'field_53c51e7aa6fde',
				'label' => 'Dribbble',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53c51e82a6fdf',
				'label' => 'Display Dribbble Posts',
				'name' => 'display_dribbble_posts',
				'type' => 'radio',
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'no',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53e225f919859',
				'label' => 'Enable Thumbnail',
				'name' => 'enable_dribbble_thumbnail',
				'type' => 'radio',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53c51e82a6fdf',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'yes',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53c51edaa6fe0',
				'label' => 'Player Name',
				'name' => 'player_name',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53c51e82a6fdf',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53c51ef3a6fe1',
				'label' => 'Dribbble Post Count',
				'name' => 'dribbble_post_count',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53c51e82a6fdf',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53c51f29a6fe2',
				'label' => 'Dribbble Refresh Cache',
				'name' => 'dribbble_refresh_cache',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53c51e82a6fdf',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 50,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_53e1d93cd027b',
				'label' => 'Instagram',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_53e1d948d027c',
				'label' => 'Display Instagram',
				'name' => 'display_instagram',
				'type' => 'radio',
				'choices' => array (
					'yes' => 'Yes',
					'no' => 'No',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'no',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53e1d9ddd027d',
				'label' => 'Instagram Name',
				'name' => 'instagram_name',
				'type' => 'text',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53e1d948d027c',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53e1da15d027e',
				'label' => 'Instagram Post Count',
				'name' => 'instagram_post_count',
				'type' => 'number',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53e1d948d027c',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 5,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 25,
				'step' => '',
			),
			array (
				'key' => 'field_53e1da49d027f',
				'label' => 'Instagram Refresh Cache',
				'name' => 'instagram_refresh_cache',
				'type' => 'number',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53e1d948d027c',
							'operator' => '==',
							'value' => 'yes',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 30,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'minutes',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5324a3a140542',
				'label' => 'Shortcode',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5324a3b440543',
				'label' => 'Shortcode',
				'name' => 'shortcode',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Shortcode',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5324a3f703455',
				'label' => 'Settings',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_5324a4e95a943',
				'label' => 'Character Count',
				'name' => '',
				'type' => 'message',
				'message' => '<h2 class="underlined">Character Count</h2>',
			),
			array (
				'key' => 'field_5324a40203456',
				'label' => 'Character Count',
				'name' => 'character_count_title',
				'type' => 'number',
				'default_value' => 100,
				'placeholder' => '',
				'prepend' => 'Title',
				'append' => '',
				'min' => 10,
				'max' => 100,
				'step' => '',
			),
			array (
				'key' => 'field_5324a47803457',
				'label' => 'Character Count',
				'name' => 'character_count_content',
				'type' => 'number',
				'default_value' => 200,
				'placeholder' => '',
				'prepend' => 'Content',
				'append' => '',
				'min' => 10,
				'max' => 500,
				'step' => '',
			),
			array (
				'key' => 'field_532dc352ff9ef',
				'label' => 'Text',
				'name' => '',
				'type' => 'message',
				'message' => '<h2 class="underlined">Text</h2>',
			),
			array (
				'key' => 'field_532dc371ff9f0',
				'label' => 'Begin Text',
				'name' => 'begin_text',
				'type' => 'text',
				'default_value' => 'NOW',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_532dc399ff9f1',
				'label' => 'End Text',
				'name' => 'end_text',
				'type' => 'text',
				'default_value' => 'LAUNCH',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_532dc3c5ff9f2',
				'label' => 'Footer Message',
				'name' => 'footer_message',
				'type' => 'wysiwyg',
				'default_value' => '<h4>Launched our product on 28 January, 2013</h4>
	<p>Launched our product on 28 January, 2013</p>',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'timeline',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}




if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_post',
		'title' => 'Post',
		'fields' => array (
			array (
				'key' => 'field_53bd27a28f999',
				'label' => 'Post Icon',
				'name' => 'post_icon',
				'type' => 'radio',
				'choices' => array (
					'default' => 'Default',
					'Image' => 'Image',
					'fontawesome' => 'FontAwesome',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'default',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53bd280e8f99a',
				'label' => 'Image',
				'name' => 'image',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53bd27a28f999',
							'operator' => '==',
							'value' => 'Image',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_53bd283d8f99b',
				'label' => 'FontAwesome',
				'name' => 'fontawesome',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53bd27a28f999',
							'operator' => '==',
							'value' => 'fontawesome',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_time-format',
		'title' => 'Time Format',
		'fields' => array (
			array (
				'key' => 'field_53e21fc36ead2',
				'label' => 'Time Format',
				'name' => 'time_format',
				'type' => 'text',
				'instructions' => '<em>Enter format in which you want to display your Timeline. For reference open <a href="http://php.net/manual/en/function.date.php" target="_blank">this</a></em>',
				'default_value' => 'd M Y',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53e220a76ead3',
				'label' => 'Time Ago',
				'name' => 'time_ago',
				'type' => 'radio',
				'choices' => array (
					'enable' => 'Enable',
					'disable' => 'Disable',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'disable',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_53e221256ead4',
				'label' => 'Order',
				'name' => 'order',
				'type' => 'radio',
				'choices' => array (
					'ascending' => 'Acending',
					'descending' => 'Descending',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'descending',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'timeline',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
